debug: true
server:
  port: 8088
  contextPath: /app
spring:
 application:
  name: app11

security:
  user:
    password: user
  ignored: /,/favicon.ico,/index.html,/home.html,/dashboard.html,/js/**,/css/**,/webjars/**
  sessions: ALWAYS
  oauth2:
    sso:
      loginPath: /my/login
management:
  security:
    role: HERO

logging:
  level:
    org.springframework.security: DEBUG
    com.netflix.discovery: 'OFF'

---
spring:
  profiles: default
security:
  oauth2:
    client:
      accessTokenUri: http://localhost:8081/oauth/token
      userAuthorizationUri: http://localhost:8081/oauth/authorize
      clientId: clientid01
      clientSecret: mysecret
    resource:
       userInfoUri: http://localhost:8081/user

---
spring:
  profiles: default11
security:
  oauth2:
    client:
      clientId: 84144543bbc2f99bb3f7
      clientSecret: ccd83a0386517474598dabe4c6d249a972c7b86c
      accessTokenUri: https://github.com/login/oauth/access_token
      userAuthorizationUri: https://github.com/login/oauth/authorize
      clientAuthenticationScheme: form
    resource:
      userInfoUri: https://api.github.com/user
      preferTokenInfo: false

      